# Generated by Django 5.1 on 2024-09-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_managment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managment',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
